### ISSUE TITLE
filter or whereHas

### ISSUE THREAD

**Issue by drmax24** [ttoohey/laravel-graphql-filter#3]
I think "filter" should be called "whereHas" because everything is filter.
When you choose certain attribute names for output that is filter.
When you choose certain attribute values to filter query that is a filter too.

Now you introduce "filter". Well we should call it more precisely.
Interesting library though.

**Comment by ttoohey** [comment]
Thanks for the suggestion. Naming things is hard :)

I did consider whereX() (for various values of 'X') and tried to find a precedent I could use. In the end I decided that the common feature to the existing Laravel where() functions (whereIn, whereNull, etc) is they provde access to SQL syntax that is otherwise not available. Coupled with not coming up with an 'X' that sounded right to me was enough for my name search to keep going.

In the end I was choosing between filter() and search(). I liked filter() because:
* like Collection::filter() it takes a set of records and produces a sub-set
* I see a continuous path from a UI form called a "filter", to the API argument containing the criteria entered in the form, to the method on the model to execute it. (this same argument works for 'search')

It sounds to me like you don't agree with that latter part -- everything being called "filter" makes it confusing to talk about. I can see a valid point here.

I think it's too late to change this (at least for me).
